import { createClient, Client } from "@libsql/client";
import path from "path";

// Data seed awal dari tim tech
const seedData = [
  { filter: "proxy", plugin_id: 40013, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-proxy" },
  { filter: "storage-backup", plugin_id: 40011, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-storage-backup" },
  { filter: "remote-access", plugin_id: 40015, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-remote-access" },
  { filter: "ips", plugin_id: 40029, by: "fortigate/utm/ips", siem_plugin_type: "fortigate-utm-ips" },
  { filter: "cloud-it", plugin_id: 40001, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-cloud-it" },
  { filter: "network-service", plugin_id: 40002, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-network-service" },
  { filter: "web-client", plugin_id: 40003, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-web-client" },
  { filter: "collaboration", plugin_id: 40004, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-collaboration" },
  { filter: "general-interest", plugin_id: 40005, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-general-interest" },
  { filter: "social-media", plugin_id: 40007, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-social-media" },
  { filter: "update", plugin_id: 40008, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-update" },
  { filter: "business", plugin_id: 40009, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-business" },
  { filter: "email", plugin_id: 40010, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-email" },
  { filter: "video-audio", plugin_id: 40012, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-video-audio" },
  { filter: "genai", plugin_id: 40014, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-genai" },
  { filter: "game", plugin_id: 40016, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-game" },
  { filter: "mobile", plugin_id: 40017, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-mobile" },
  { filter: "voip", plugin_id: 40018, by: "fortigate/utm/app-ctrl", siem_plugin_type: "fortigate-utm-app-ctrl-voip" },
  { filter: "ssl", plugin_id: 40030, by: "fortigate/utm/ssl", siem_plugin_type: "fortigate-utm-ssl" },
  { filter: "webfilter", plugin_id: 40031, by: "fortigate/utm/webfilter", siem_plugin_type: "fortigate-utm-webfilter" },
  { filter: "virus", plugin_id: 40032, by: "fortigate/utm/virus", siem_plugin_type: "fortigate-utm-virus" },
  { filter: "vpn", plugin_id: 40040, by: "fortigate/event/vpn", siem_plugin_type: "fortigate-event-vpn" },
  { filter: "sdwan", plugin_id: 40041, by: "fortigate/event/sdwan", siem_plugin_type: "fortigate-event-sdwan" },
  { filter: "system", plugin_id: 40042, by: "fortigate/event/system", siem_plugin_type: "fortigate-event-system" },
  { filter: "security-rating", plugin_id: 40043, by: "fortigate/event/security-rating", siem_plugin_type: "fortigate-event-security-rating" },
  { filter: "ha", plugin_id: 40044, by: "fortigate/event/ha", siem_plugin_type: "fortigate-event-ha" },
  { filter: "user", plugin_id: 40045, by: "fortigate/event/user", siem_plugin_type: "fortigate-event-user" },
  { filter: "webfilter", plugin_id: 40060, by: "fortigate/dns/webfilter", siem_plugin_type: "fortigate-dns-webfilter" },
  { filter: "", plugin_id: 40100, by: "citrix/None", siem_plugin_type: "citrix" },
  { filter: "http-load-balancer", plugin_id: 40300, by: "gcp/cloudarmor/http-load-balancer", siem_plugin_type: "gcp-cloudarmor-http-load-balancer" },
  { filter: "gcs-bucket", plugin_id: 40310, by: "gcp/audit/gcs-bucket", siem_plugin_type: "gcp-audit-gcs-bucket" },
  { filter: "gce-instance-group-manager", plugin_id: 40311, by: "gcp/audit/gce-instance-group-manager", siem_plugin_type: "gcp-audit-gce-instance-group-manager" },
  { filter: "gce-instance", plugin_id: 40312, by: "gcp/audit/gce-instance", siem_plugin_type: "gcp-audit-gce-instance" },
  { filter: "bigquery-resource", plugin_id: 40313, by: "gcp/audit/bigquery-resource", siem_plugin_type: "gcp-audit-bigquery-resource" },
  { filter: "gce-image", plugin_id: 40314, by: "gcp/audit/gce-image", siem_plugin_type: "gcp-audit-gce-image" },
  { filter: "gce-disk", plugin_id: 40315, by: "gcp/audit/gce-disk", siem_plugin_type: "gcp-audit-gce-disk" },
  { filter: "gce-backend-service", plugin_id: 40316, by: "gcp/audit/gce-backend-service", siem_plugin_type: "gcp-audit-gce-backend-service" },
  { filter: "gce-forwarding-rule", plugin_id: 40317, by: "gcp/audit/gce-forwarding-rule", siem_plugin_type: "gcp-audit-gce-forwarding-rule" },
  { filter: "gce-reserved-address", plugin_id: 40318, by: "gcp/audit/gce-reserved-address", siem_plugin_type: "gcp-audit-gce-reserved-address" },
  { filter: "gce-instance-group", plugin_id: 40319, by: "gcp/audit/gce-instance-group", siem_plugin_type: "gcp-audit-gce-instance-group" },
  { filter: "gce-network", plugin_id: 40320, by: "gcp/audit/gce-network", siem_plugin_type: "gcp-audit-gce-network" },
  { filter: "gce-health-check", plugin_id: 40321, by: "gcp/audit/gce-health-check", siem_plugin_type: "gcp-audit-gce-health-check" },
  { filter: "gce-route", plugin_id: 40322, by: "gcp/audit/gce-route", siem_plugin_type: "gcp-audit-gce-route" },
  { filter: "gce-url-map", plugin_id: 40323, by: "gcp/audit/gce-url-map", siem_plugin_type: "gcp-audit-gce-url-map" },
  { filter: "gce-target-https-proxy", plugin_id: 40324, by: "gcp/audit/gce-target-https-proxy", siem_plugin_type: "gcp-audit-gce-target-https-proxy" },
  { filter: "gce-subnetwork", plugin_id: 40325, by: "gcp/audit/gce-subnetwork", siem_plugin_type: "gcp-audit-gce-subnetwork" },
  { filter: "gce-firewall-rule", plugin_id: 40326, by: "gcp/audit/gce-firewall-rule", siem_plugin_type: "gcp-audit-gce-firewall-rule" },
  { filter: "gce-ssl-certificate", plugin_id: 40327, by: "gcp/audit/gce-ssl-certificate", siem_plugin_type: "gcp-audit-gce-ssl-certificate" },
  { filter: "gce-target-http-proxy", plugin_id: 40328, by: "gcp/audit/gce-target-http-proxy", siem_plugin_type: "gcp-audit-gce-target-http-proxy" },
  { filter: "gce-operation", plugin_id: 40329, by: "gcp/audit/gce-operation", siem_plugin_type: "gcp-audit-gce-operation" },
  { filter: "gce-project", plugin_id: 40330, by: "gcp/audit/gce-project", siem_plugin_type: "gcp-audit-gce-project" },
  { filter: "gce-router", plugin_id: 40331, by: "gcp/audit/gce-router", siem_plugin_type: "gcp-audit-gce-router" },
  { filter: "gce-target-pool", plugin_id: 40332, by: "gcp/audit/gce-target-pool", siem_plugin_type: "gcp-audit-gce-target-pool" },
  { filter: "gce-instance-template", plugin_id: 40333, by: "gcp/audit/gce-instance-template", siem_plugin_type: "gcp-audit-gce-instance-template" },
  { filter: "gce-resource-policy", plugin_id: 40334, by: "gcp/audit/gce-resource-policy", siem_plugin_type: "gcp-audit-gce-resource-policy" },
  { filter: "gce-target-ssl-proxy", plugin_id: 40336, by: "gcp/audit/gce-target-ssl-proxy", siem_plugin_type: "gcp-audit-gce-target-ssl-proxy" },
  { filter: "gce-backend-bucket", plugin_id: 40337, by: "gcp/audit/gce-backend-bucket", siem_plugin_type: "gcp-audit-gce-backend-bucket" },
  { filter: "", plugin_id: 40500, by: "socradar/None", siem_plugin_type: "socradar" },
  { filter: "", plugin_id: 40501, by: "proofpoint/None", siem_plugin_type: "proofpoint" },
  { filter: "firewallcustom", plugin_id: 40510, by: "cloudflare/firewallcustom", siem_plugin_type: "cloudflare-firewallcustom" },
  { filter: "firewallmanaged", plugin_id: 40512, by: "cloudflare/firewallmanaged", siem_plugin_type: "cloudflare-firewallmanaged" },
  { filter: "ratelimit", plugin_id: 40511, by: "cloudflare/ratelimit", siem_plugin_type: "cloudflare-ratelimit" },
  { filter: "", plugin_id: 40550, by: "akamai/None", siem_plugin_type: "akamai" },
  { filter: "waf", plugin_id: 40513, by: "cloudflare/waf", siem_plugin_type: "cloudflare-waf" },
  { filter: "smartdefense", plugin_id: 40560, by: "checkpoint/smartdefense", siem_plugin_type: "checkpoint-smartdefense" },
  { filter: "connectra", plugin_id: 40563, by: "checkpoint/connectra", siem_plugin_type: "checkpoint-connectra" },
  { filter: "new-anti-virus", plugin_id: 40561, by: "checkpoint/new-anti-virus", siem_plugin_type: "checkpoint-new-anti-virus" },
  { filter: "anti-malware", plugin_id: 40562, by: "checkpoint/anti-malware", siem_plugin_type: "checkpoint-anti-malware" },
  { filter: "azureactivedirectory", plugin_id: 40600, by: "microsoft365/None", siem_plugin_type: "microsoft365-azureactivedirectory" },
  { filter: "exchange", plugin_id: 40601, by: "microsoft365/", siem_plugin_type: "microsoft365-exchange" },
  { filter: "sharepoint", plugin_id: 40602, by: "microsoft365/", siem_plugin_type: "microsoft365-sharepoint" },
  { filter: "onedrive", plugin_id: 40603, by: "microsoft365/", siem_plugin_type: "microsoft365-onedrive" },
  { filter: "microsoftteams", plugin_id: 40604, by: "microsoft365/", siem_plugin_type: "microsoft365-microsoftteams" },
  { filter: "microsoftforms", plugin_id: 40606, by: "microsoft365/", siem_plugin_type: "microsoft365-microsoftforms" },
  { filter: "publicendpoint", plugin_id: 40605, by: "microsoft365/", siem_plugin_type: "microsoft365-publicendpoint" },
  { filter: "powerplatform", plugin_id: 40607, by: "microsoft365/", siem_plugin_type: "microsoft365-powerplatform" },
  { filter: "planner", plugin_id: 40608, by: "microsoft365/", siem_plugin_type: "microsoft365-planner" },
  { filter: "endpoint", plugin_id: 40609, by: "microsoft365/", siem_plugin_type: "microsoft365-endpoint" },
  { filter: "aip", plugin_id: 40610, by: "microsoft365/", siem_plugin_type: "microsoft365-aip" },
  { filter: "microsofttodo", plugin_id: 40611, by: "microsoft365/", siem_plugin_type: "microsoft365-microsofttodo" },
  { filter: "copilot", plugin_id: 40612, by: "microsoft365/", siem_plugin_type: "microsoft365-copilot" },
  { filter: "securitycompliancecenter", plugin_id: 40613, by: "microsoft365/", siem_plugin_type: "microsoft365-securitycompliancecenter" },
  { filter: "attacksimulation", plugin_id: 40614, by: "microsoft365/", siem_plugin_type: "microsoft365-attacksimulation" },
  { filter: "complianceposturemanagement", plugin_id: 40615, by: "microsoft365/", siem_plugin_type: "microsoft365-complianceposturemanagement" },
  { filter: "threatintelligence", plugin_id: 40616, by: "microsoft365/", siem_plugin_type: "microsoft365-threatintelligence" },
  { filter: "microsoftflow", plugin_id: 40617, by: "microsoft365/", siem_plugin_type: "microsoft365-microsoftflow" },
  { filter: "powerbi", plugin_id: 40618, by: "microsoft365/", siem_plugin_type: "microsoft365-powerbi" },
  { filter: "projectfortheweb", plugin_id: 40619, by: "microsoft365/", siem_plugin_type: "microsoft365-projectfortheweb" },
  { filter: "yammer", plugin_id: 40620, by: "microsoft365/", siem_plugin_type: "microsoft365-yammer" },
  { filter: "airinvestigation", plugin_id: 40621, by: "microsoft365/", siem_plugin_type: "microsoft365-airinvestigation" },
  { filter: "quarantine", plugin_id: 40622, by: "microsoft365/", siem_plugin_type: "microsoft365-quarantine" },
  { filter: "microsoftplaces", plugin_id: 40623, by: "microsoft365/", siem_plugin_type: "microsoft365-microsoftplaces" },
  { filter: "mip", plugin_id: 40624, by: "microsoft365/", siem_plugin_type: "microsoft365-mip" },
  { filter: "mesh", plugin_id: 40625, by: "microsoft365/", siem_plugin_type: "microsoft365-mesh" },
  { filter: "dlpsensitiveinformationtype", plugin_id: 40626, by: "microsoft365/", siem_plugin_type: "microsoft365-dlpsensitiveinformationtype" },
  { filter: "sip", plugin_id: 40700, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-sip" },
  { filter: "ldap", plugin_id: 40701, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ldap" },
  { filter: "mssql-db-unencrypted", plugin_id: 40702, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-mssql-db-unencrypted" },
  { filter: "ssh", plugin_id: 40703, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ssh" },
  { filter: "web-browsing", plugin_id: 40704, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-web-browsing" },
  { filter: "ms-ds-smbv3", plugin_id: 40705, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ms-ds-smbv3" },
  { filter: "incomplete", plugin_id: 40706, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-incomplete" },
  { filter: "ms-rdp", plugin_id: 40707, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ms-rdp" },
  { filter: "outlook-web", plugin_id: 40708, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-outlook-web" },
  { filter: "http-proxy", plugin_id: 40709, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-http-proxy" },
  { filter: "ssl", plugin_id: 40710, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ssl" },
  { filter: "postgres", plugin_id: 40711, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-postgres" },
  { filter: "dns-base", plugin_id: 40712, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-dns-base" },
  { filter: "rpc", plugin_id: 40713, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-rpc" },
  { filter: "tftp", plugin_id: 40714, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-tftp" },
  { filter: "portmapper", plugin_id: 40715, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-portmapper" },
  { filter: "google-base", plugin_id: 40716, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-google-base" },
  { filter: "ftp", plugin_id: 40717, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ftp" },
  { filter: "vmware", plugin_id: 40718, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-vmware" },
  { filter: "activesync", plugin_id: 40719, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-activesync" },
  { filter: "ms-teams", plugin_id: 40720, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ms-teams" },
  { filter: "apache-jserv", plugin_id: 40721, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-apache-jserv" },
  { filter: "microsoft-excel", plugin_id: 40722, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-microsoft-excel" },
  { filter: "ms-onedrive-business", plugin_id: 40723, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ms-onedrive-business" },
  { filter: "gmail-base", plugin_id: 40724, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-gmail-base" },
  { filter: "imap", plugin_id: 40725, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-imap" },
  { filter: "ms-netlogon", plugin_id: 40726, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-ms-netlogon" },
  { filter: "radius", plugin_id: 40727, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-radius" },
  { filter: "webdav", plugin_id: 40728, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability-webdav" },
  { filter: "dns-base", plugin_id: 40740, by: "paloalto/threat/spyware", siem_plugin_type: "paloalto-threat-spyware-dns-base" },
  { filter: "web-browsing", plugin_id: 40741, by: "paloalto/threat/spyware", siem_plugin_type: "paloalto-threat-spyware-web-browsing" },
  { filter: "dns-wa-web", plugin_id: 40742, by: "paloalto/threat/spyware", siem_plugin_type: "paloalto-threat-spyware-dns-wa-web" },
  { filter: "stratum-mining-protocol", plugin_id: 40743, by: "paloalto/threat/spyware", siem_plugin_type: "paloalto-threat-spyware-stratum-mining-protocol" },
  { filter: "unknown-tcp", plugin_id: 40744, by: "paloalto/threat/spyware", siem_plugin_type: "paloalto-threat-spyware-unknown-tcp" },
  { filter: "ms-update", plugin_id: 40760, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-ms-update" },
  { filter: "ms-ds-smbv3", plugin_id: 40761, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-ms-ds-smbv3" },
  { filter: "http-proxy", plugin_id: 40762, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-http-proxy" },
  { filter: "web-browsing", plugin_id: 40763, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-web-browsing" },
  { filter: "ocsp", plugin_id: 40764, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-ocsp" },
  { filter: "adobe-update", plugin_id: 40765, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-adobe-update" },
  { filter: "symantec-endpoint-manager", plugin_id: 40766, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-symantec-endpoint-manager" },
  { filter: "smtp-base", plugin_id: 40767, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-smtp-base" },
  { filter: "mcafee-update", plugin_id: 40768, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-mcafee-update" },
  { filter: "google-base", plugin_id: 40769, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-google-base" },
  { filter: "symantec-av-update", plugin_id: 40770, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-symantec-av-update" },
  { filter: "ms-ds-smbv2", plugin_id: 40771, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-ms-ds-smbv2" },
  { filter: "dnf", plugin_id: 40772, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-dnf" },
  { filter: "sharepoint-base", plugin_id: 40773, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-sharepoint-base" },
  { filter: "http-audio", plugin_id: 40774, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-http-audio" },
  { filter: "apt-get", plugin_id: 40775, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-apt-get" },
  { filter: "ms-sms", plugin_id: 40776, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-ms-sms" },
  { filter: "flash", plugin_id: 40777, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-flash" },
  { filter: "msrpc-base", plugin_id: 40778, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-msrpc-base" },
  { filter: "outlook-web", plugin_id: 40779, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-outlook-web" },
  { filter: "git-uploading", plugin_id: 40780, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-git-uploading" },
  { filter: "unknown-tcp", plugin_id: 40781, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-unknown-tcp" },
  { filter: "whatsapp-base", plugin_id: 40782, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file-whatsapp-base" },
  { filter: "http-proxy", plugin_id: 40800, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-http-proxy" },
  { filter: "whatsapp-web", plugin_id: 40801, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-whatsapp-web" },
  { filter: "ms-onedrive-base", plugin_id: 40802, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-ms-onedrive-base" },
  { filter: "web-browsing", plugin_id: 40803, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-web-browsing" },
  { filter: "codeium", plugin_id: 40804, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-codeium" },
  { filter: "ms-office365-copilot", plugin_id: 40805, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-ms-office365-copilot" },
  { filter: "ssl", plugin_id: 40806, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-ssl" },
  { filter: "google-docs-base", plugin_id: 40807, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-google-docs-base" },
  { filter: "openai-chatgpt", plugin_id: 40808, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-openai-chatgpt" },
  { filter: "google-drive-web-base", plugin_id: 40809, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-google-drive-web-base" },
  { filter: "airdroid", plugin_id: 40810, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-airdroid" },
  { filter: "bing-ai-base", plugin_id: 40811, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-bing-ai-base" },
  { filter: "github-copilot", plugin_id: 40812, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-github-copilot" },
  { filter: "xbox-live", plugin_id: 40813, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-xbox-live" },
  { filter: "google-base", plugin_id: 40814, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-google-base" },
  { filter: "teamviewer-base", plugin_id: 40815, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-teamviewer-base" },
  { filter: "boxnet-base", plugin_id: 40816, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-boxnet-base" },
  { filter: "imgur-base", plugin_id: 40817, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-imgur-base" },
  { filter: "dropbox-base", plugin_id: 40818, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-dropbox-base" },
  { filter: "google-gemini", plugin_id: 40819, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-google-gemini" },
  { filter: "teamviewer-web", plugin_id: 40820, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-teamviewer-web" },
  { filter: "huggingface-base", plugin_id: 40821, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-huggingface-base" },
  { filter: "smtp-base", plugin_id: 40822, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-smtp-base" },
  { filter: "cloudinary-base", plugin_id: 40823, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-cloudinary-base" },
  { filter: "lovable", plugin_id: 40824, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-lovable" },
  { filter: "shodan", plugin_id: 40825, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-shodan" },
  { filter: "apache-solr", plugin_id: 40826, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-apache-solr" },
  { filter: "helpwire", plugin_id: 40827, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-helpwire" },
  { filter: "filestack-base", plugin_id: 40828, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-filestack-base" },
  { filter: "wasabi", plugin_id: 40829, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-wasabi" },
  { filter: "wetransfer-base", plugin_id: 40830, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-wetransfer-base" },
  { filter: "openai-sora", plugin_id: 40831, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-openai-sora" },
  { filter: "claude-base", plugin_id: 40832, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-claude-base" },
  { filter: "elevenlabs-base", plugin_id: 40833, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-elevenlabs-base" },
  { filter: "openai-api", plugin_id: 40834, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-openai-api" },
  { filter: "openai-base", plugin_id: 40835, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-openai-base" },
  { filter: "socks", plugin_id: 40836, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url-socks" },
  { filter: "securitycompliancerbac", plugin_id: 40627, by: "microsoft365/", siem_plugin_type: "microsoft365-securitycompliancerbac" },
  { filter: "", plugin_id: 40640, by: "microsoft365/Identity Protection", siem_plugin_type: "microsoft365-identity-protection" },
  { filter: "observed-attack-techniques", plugin_id: 40900, by: "trendmicro/vision one/Observed Attack Techniques", siem_plugin_type: "trendmicro-vision-one-observed-attack-techniques" },
  { filter: "l7ddos", plugin_id: 40514, by: "cloudflare/l7ddos", siem_plugin_type: "cloudflare-l7ddos" },
  { filter: "zonelockdown", plugin_id: 40515, by: "cloudflare/zoneLockdown", siem_plugin_type: "cloudflare-zonelockdown" },
  { filter: "bic", plugin_id: 40517, by: "cloudflare/bic", siem_plugin_type: "cloudflare-bic" },
  { filter: "dlp", plugin_id: 40518, by: "cloudflare/dlp", siem_plugin_type: "cloudflare-dlp" },
  { filter: "apishieldsequencemitigation", plugin_id: 40519, by: "cloudflare/apiShieldSequenceMitigation", siem_plugin_type: "cloudflare-apishieldsequencemitigation" },
  { filter: "apishieldschemavalidation", plugin_id: 40516, by: "cloudflare/apiShieldSchemaValidation", siem_plugin_type: "cloudflare-apishieldschemavalidation" },
  { filter: "", plugin_id: 41100, by: "zoom/", siem_plugin_type: "zoom" },
  { filter: "vulnerability", plugin_id: 40850, by: "paloalto/threat/vulnerability", siem_plugin_type: "paloalto-threat-vulnerability" },
  { filter: "spyware", plugin_id: 40851, by: "paloalto/threat/spyware", siem_plugin_type: "paloalto-threat-spyware" },
  { filter: "file", plugin_id: 40852, by: "paloalto/threat/file", siem_plugin_type: "paloalto-threat-file" },
  { filter: "url", plugin_id: 40853, by: "paloalto/threat/url", siem_plugin_type: "paloalto-threat-url" },
  { filter: "", plugin_id: 41110, by: "imperva/incapsula", siem_plugin_type: "imperva-incapsula" },
  { filter: "core-directory", plugin_id: 40650, by: "azuread/Audit/Core Directory", siem_plugin_type: "azuread-audit-core-directory" },
  { filter: "account-provisioning", plugin_id: 40651, by: "azuread/Audit/Account Provisioning", siem_plugin_type: "azuread-audit-account-provisioning" },
  { filter: "device-registration-service", plugin_id: 40652, by: "azuread/Audit/Device Registration Service", siem_plugin_type: "azuread-audit-device-registration-service" },
  { filter: "authentication-methods", plugin_id: 40653, by: "azuread/Audit/Authentication Methods", siem_plugin_type: "azuread-audit-authentication-methods" },
  { filter: "self-service-password-management", plugin_id: 40654, by: "azuread/Audit/Self-service Password Management", siem_plugin_type: "azuread-audit-self-service-password-management" },
  { filter: "self-service-group-management", plugin_id: 40655, by: "azuread/Audit/Self-service Group Management", siem_plugin_type: "azuread-audit-self-service-group-management" },
  { filter: "pim", plugin_id: 40656, by: "azuread/Audit/PIM", siem_plugin_type: "azuread-audit-pim" },
  { filter: "b2c", plugin_id: 40657, by: "azuread/Audit/B2C", siem_plugin_type: "azuread-audit-b2c" },
  { filter: "identity-protection", plugin_id: 40658, by: "azuread/Audit/Identity Protection", siem_plugin_type: "azuread-audit-identity-protection" },
  { filter: "azure-mfa", plugin_id: 40659, by: "azuread/Audit/Azure MFA", siem_plugin_type: "azuread-audit-azure-mfa" },
  { filter: "aad-management-ux", plugin_id: 40660, by: "azuread/Audit/AAD Management UX", siem_plugin_type: "azuread-audit-aad-management-ux" },
  { filter: "conditional-access", plugin_id: 40661, by: "azuread/Audit/Conditional Access", siem_plugin_type: "azuread-audit-conditional-access" },
  { filter: "b2b-auth", plugin_id: 40662, by: "azuread/Audit/B2B Auth", siem_plugin_type: "azuread-audit-b2b-auth" },
  { filter: "invited-users", plugin_id: 40663, by: "azuread/Audit/Invited Users", siem_plugin_type: "azuread-audit-invited-users" },
  { filter: "application-proxy", plugin_id: 40664, by: "azuread/Audit/Application Proxy", siem_plugin_type: "azuread-audit-application-proxy" },
  { filter: "infrastructure", plugin_id: 41200, by: "sophos/Application", siem_plugin_type: "sophos-application-infrastructure" },
  { filter: "mobile-applications", plugin_id: 41201, by: "sophos/Application", siem_plugin_type: "sophos-application-mobile-applications" },
  { filter: "general-internet", plugin_id: 41202, by: "sophos/Application", siem_plugin_type: "sophos-application-general-internet" },
  { filter: "file-transfer", plugin_id: 41203, by: "sophos/Application", siem_plugin_type: "sophos-application-file-transfer" },
  { filter: "general-business", plugin_id: 41204, by: "sophos/Application", siem_plugin_type: "sophos-application-general-business" },
  { filter: "social-networking", plugin_id: 41205, by: "sophos/Application", siem_plugin_type: "sophos-application-social-networking" },
  { filter: "conferencing", plugin_id: 41206, by: "sophos/Application", siem_plugin_type: "sophos-application-conferencing" },
  { filter: "streaming-media", plugin_id: 41207, by: "sophos/Application", siem_plugin_type: "sophos-application-streaming-media" },
  { filter: "instant-messenger", plugin_id: 41208, by: "sophos/Application", siem_plugin_type: "sophos-application-instant-messenger" },
  { filter: "proxy-and-tunnel", plugin_id: 41209, by: "sophos/Application", siem_plugin_type: "sophos-application-proxy-and-tunnel" },
  { filter: "remote-access", plugin_id: 41210, by: "sophos/Application", siem_plugin_type: "sophos-application-remote-access" },
  { filter: "web-mail", plugin_id: 41211, by: "sophos/Application", siem_plugin_type: "sophos-application-web-mail" },
  { filter: "software-update", plugin_id: 41212, by: "sophos/Application", siem_plugin_type: "sophos-application-software-update" },
  { filter: "e-commerce", plugin_id: 41213, by: "sophos/Application", siem_plugin_type: "sophos-application-e-commerce" },
  { filter: "p2p", plugin_id: 41214, by: "sophos/Application", siem_plugin_type: "sophos-application-p2p" },
  { filter: "generative-ai", plugin_id: 41215, by: "sophos/Application", siem_plugin_type: "sophos-application-generative-ai" },
  { filter: "storage-and-backup", plugin_id: 41216, by: "sophos/Application", siem_plugin_type: "sophos-application-storage-and-backup" },
  { filter: "gaming", plugin_id: 41217, by: "sophos/Application", siem_plugin_type: "sophos-application-gaming" },
  { filter: "network-services", plugin_id: 41218, by: "sophos/Application", siem_plugin_type: "sophos-application-network-services" },
  { filter: "voip", plugin_id: 41219, by: "sophos/Application", siem_plugin_type: "sophos-application-voip" },
  { filter: "web-application-firewall", plugin_id: 41360, by: "sophos/WAF/Web Application Firewall", siem_plugin_type: "sophos-waf-web-application-firewall" },
  { filter: "firewall-authentication", plugin_id: 41371, by: "sophos/Event/Firewall Authentication", siem_plugin_type: "sophos-event-firewall-authentication" },
  { filter: "ssl-vpn-authentication", plugin_id: 41374, by: "sophos/Event/SSL VPN Authentication", siem_plugin_type: "sophos-event-ssl-vpn-authentication" },
  { filter: "gateway", plugin_id: 41381, by: "sophos/Event/Gateway", siem_plugin_type: "sophos-event-gateway" },
  { filter: "sandbox", plugin_id: 41410, by: "sophos/Sandbox", siem_plugin_type: "sophos-sandbox" },
  { filter: "anti-spam", plugin_id: 41411, by: "sophos/Anti-Spam", siem_plugin_type: "sophos-anti-spam" },
  { filter: "atp", plugin_id: 41412, by: "sophos/ATP", siem_plugin_type: "sophos-atp" },
  { filter: "anti-virus", plugin_id: 41413, by: "sophos/Anti-Virus", siem_plugin_type: "sophos-anti-virus" },
  { filter: "guardduty", plugin_id: 41500, by: "coralogix/aws/guardduty", siem_plugin_type: "coralogix-aws-guardduty" },
  { filter: "", plugin_id: 42000, by: "threatmon/", siem_plugin_type: "threatmon" },
  { filter: "", plugin_id: 42010, by: "flowmon/", siem_plugin_type: "flowmon" },
  { filter: "", plugin_id: 42020, by: "crowdstrike/", siem_plugin_type: "crowdstrike" }
];

let dbInstance: Client | null = null;

export default async function getDb() {
  if (dbInstance) return dbInstance;

  const dbPath = path.resolve(process.cwd(), "plugins.db");
  const db = createClient({
    url: `file:${dbPath}`,
  });

  // Inisialisasi tabel
  await db.execute(`
    CREATE TABLE IF NOT EXISTS plugins (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      filter TEXT,
      plugin_id INTEGER UNIQUE,
      "by" TEXT,
      siem_plugin_type TEXT
    );
  `);

  const checkEmpty = await db.execute("SELECT COUNT(*) as count FROM plugins");
  const count = checkEmpty.rows[0].count as number;
  
  if (count === 0) {
    const stmts = seedData.map(item => ({
      sql: `INSERT INTO plugins (filter, plugin_id, "by", siem_plugin_type) VALUES (?, ?, ?, ?)`,
      args: [item.filter, item.plugin_id, item.by, item.siem_plugin_type]
    }));
    
    await db.batch(stmts);
  }

  dbInstance = db;
  return dbInstance;
}
